"""
Curated list of small-cap and mid-cap publicly-traded U.S. government contractors.

Each entry has:
  ticker:        stock symbol (used for market cap lookup via yfinance)
  name:          display name shown in alerts
  match_terms:   list of UPPERCASE substrings; if any one appears in a normalized
                 recipient name returned by USAspending, it counts as a match.
                 Use specific phrases (e.g. "MERCURY SYSTEMS"), not bare words
                 like "MERCURY", to avoid false positives.
  exclude_terms: optional list; if any one appears, the match is rejected.

Note on cap bands: the cap_band filter in market_data.py automatically drops
large-caps at scan time, so it's safe to include borderline names. Some of
these (CACI, SAIC, HII, AKAM) flirt with large-cap depending on the day.
"""

WATCHLIST = [
    # ============ DEFENSE / AEROSPACE ============
    {"ticker": "KTOS", "name": "Kratos Defense & Security Solutions",
     "match_terms": ["KRATOS"]},
    {"ticker": "MRCY", "name": "Mercury Systems",
     "match_terms": ["MERCURY SYSTEMS", "MERCURY DEFENSE"]},
    {"ticker": "AVAV", "name": "AeroVironment",
     "match_terms": ["AEROVIRONMENT"]},
    {"ticker": "DRS",  "name": "Leonardo DRS",
     "match_terms": ["LEONARDO DRS", "DRS NETWORK", "DRS LAUREL", "DRS RADA"]},
    {"ticker": "VVX",  "name": "V2X Inc",
     "match_terms": ["V2X INC", "VECTRUS"]},
    {"ticker": "PSN",  "name": "Parsons Corporation",
     "match_terms": ["PARSONS GOVERNMENT", "PARSONS CORPORATION"]},
    {"ticker": "CACI", "name": "CACI International",
     "match_terms": ["CACI"]},
    {"ticker": "SAIC", "name": "Science Applications Intl",
     "match_terms": ["SCIENCE APPLICATIONS INTERNATIONAL"]},
    {"ticker": "ICFI", "name": "ICF International",
     "match_terms": ["ICF INCORPORATED", "ICF CONSULTING", "ICF INC "]},
    {"ticker": "MMS",  "name": "Maximus",
     "match_terms": ["MAXIMUS"]},
    {"ticker": "ATRO", "name": "Astronics",
     "match_terms": ["ASTRONICS"]},
    {"ticker": "CW",   "name": "Curtiss-Wright",
     "match_terms": ["CURTISS-WRIGHT", "CURTISS WRIGHT"]},
    {"ticker": "DCO",  "name": "Ducommun",
     "match_terms": ["DUCOMMUN"]},
    {"ticker": "BWXT", "name": "BWX Technologies",
     "match_terms": ["BWX TECHNOLOGIES", "BWXT"]},
    {"ticker": "HII",  "name": "Huntington Ingalls Industries",
     "match_terms": ["HUNTINGTON INGALLS"]},
    {"ticker": "VSEC", "name": "VSE Corporation",
     "match_terms": ["VSE CORPORATION"]},
    {"ticker": "WWD",  "name": "Woodward Inc",
     "match_terms": ["WOODWARD INC", "WOODWARD HRT"]},
    {"ticker": "AIR",  "name": "AAR Corp",
     "match_terms": ["AAR GOVERNMENT", "AAR CORP", "AAR MANUFACTURING"]},
    {"ticker": "MOG-A","name": "Moog Inc",
     "match_terms": ["MOOG INC"]},
    {"ticker": "HXL",  "name": "Hexcel",
     "match_terms": ["HEXCEL"]},
    {"ticker": "ESLT", "name": "Elbit Systems",
     "match_terms": ["ELBIT SYSTEMS OF AMERICA", "ELBIT AMERICA"]},
    {"ticker": "SPR",  "name": "Spirit AeroSystems",
     "match_terms": ["SPIRIT AEROSYSTEMS"]},
    {"ticker": "TGI",  "name": "Triumph Group",
     "match_terms": ["TRIUMPH GROUP", "TRIUMPH AEROSTRUCTURES"]},
    {"ticker": "OSK",  "name": "Oshkosh Corporation",
     "match_terms": ["OSHKOSH CORPORATION", "OSHKOSH DEFENSE"]},
    {"ticker": "ALSN", "name": "Allison Transmission",
     "match_terms": ["ALLISON TRANSMISSION"]},
    {"ticker": "CDRE", "name": "Cadre Holdings",
     "match_terms": ["CADRE HOLDINGS", "SAFARILAND"]},
    {"ticker": "NPK",  "name": "National Presto Industries",
     "match_terms": ["NATIONAL PRESTO", "AMTEC CORP"]},

    # ============ SPACE / SATELLITES ============
    {"ticker": "RKLB", "name": "Rocket Lab USA",
     "match_terms": ["ROCKET LAB"]},
    {"ticker": "ASTS", "name": "AST SpaceMobile",
     "match_terms": ["AST SPACEMOBILE", "AST AND SCIENCE"]},
    {"ticker": "IRDM", "name": "Iridium Communications",
     "match_terms": ["IRIDIUM COMMUNICATIONS", "IRIDIUM SATELLITE"]},
    {"ticker": "VSAT", "name": "Viasat",
     "match_terms": ["VIASAT"]},
    {"ticker": "GSAT", "name": "Globalstar",
     "match_terms": ["GLOBALSTAR"]},
    {"ticker": "CMTL", "name": "Comtech Telecommunications",
     "match_terms": ["COMTECH TELECOMMUNICATIONS", "COMTECH SYSTEMS", "COMTECH EF DATA"]},
    {"ticker": "KVHI", "name": "KVH Industries",
     "match_terms": ["KVH INDUSTRIES"]},
    {"ticker": "RDW",  "name": "Redwire",
     "match_terms": ["REDWIRE"]},
    {"ticker": "PL",   "name": "Planet Labs",
     "match_terms": ["PLANET LABS"]},
    {"ticker": "BKSY", "name": "BlackSky Technology",
     "match_terms": ["BLACKSKY"]},
    {"ticker": "SPIR", "name": "Spire Global",
     "match_terms": ["SPIRE GLOBAL"]},
    {"ticker": "MAXR", "name": "Maxar Intelligence",
     "match_terms": ["MAXAR INTELLIGENCE", "MAXAR TECHNOLOGIES", "MAXAR SPACE"]},

    # ============ IT SERVICES / CYBER / SOFTWARE ============
    {"ticker": "TYL",  "name": "Tyler Technologies",
     "match_terms": ["TYLER TECHNOLOGIES"]},
    {"ticker": "VRNT", "name": "Verint Systems",
     "match_terms": ["VERINT"]},
    {"ticker": "TENB", "name": "Tenable Holdings",
     "match_terms": ["TENABLE"]},
    {"ticker": "RPD",  "name": "Rapid7",
     "match_terms": ["RAPID7", "RAPID 7"]},
    {"ticker": "VRNS", "name": "Varonis Systems",
     "match_terms": ["VARONIS"]},
    {"ticker": "DGII", "name": "Digi International",
     "match_terms": ["DIGI INTERNATIONAL"]},
    {"ticker": "PRGS", "name": "Progress Software",
     "match_terms": ["PROGRESS SOFTWARE"]},
    {"ticker": "DXC",  "name": "DXC Technology",
     "match_terms": ["DXC TECHNOLOGY"]},
    {"ticker": "ASGN", "name": "ASGN Incorporated",
     "match_terms": ["ECS FEDERAL", "ASGN INCORPORATED"]},
    {"ticker": "EXLS", "name": "ExlService Holdings",
     "match_terms": ["EXLSERVICE"]},
    {"ticker": "NVEE", "name": "NV5 Global",
     "match_terms": ["NV5"]},
    {"ticker": "CLVT", "name": "Clarivate",
     "match_terms": ["CLARIVATE"]},
    {"ticker": "CYBR", "name": "CyberArk Software",
     "match_terms": ["CYBERARK"]},
    {"ticker": "QLYS", "name": "Qualys",
     "match_terms": ["QUALYS"]},
    {"ticker": "AVPT", "name": "AvePoint",
     "match_terms": ["AVEPOINT"]},
    {"ticker": "DDD",  "name": "3D Systems",
     "match_terms": ["3D SYSTEMS"]},
    {"ticker": "VYX",  "name": "NCR Voyix",
     "match_terms": ["NCR VOYIX"]},
    {"ticker": "DOMO", "name": "Domo Inc",
     "match_terms": ["DOMO INC"]},
    {"ticker": "NABL", "name": "N-able",
     "match_terms": ["N-ABLE", "N ABLE"]},
    {"ticker": "CNDT", "name": "Conduent",
     "match_terms": ["CONDUENT"]},
    {"ticker": "MITK", "name": "Mitek Systems",
     "match_terms": ["MITEK SYSTEMS"]},
    {"ticker": "AKAM", "name": "Akamai Technologies",
     "match_terms": ["AKAMAI"]},
    {"ticker": "DLHC", "name": "DLH Holdings",
     "match_terms": ["DLH HOLDINGS", "DLH SOLUTIONS", "DLH CORP"]},

    # ============ HEALTHCARE / EDUCATION GOV CONTRACTORS ============
    {"ticker": "HCSG", "name": "Healthcare Services Group",
     "match_terms": ["HEALTHCARE SERVICES GROUP"]},
    {"ticker": "EVH",  "name": "Evolent Health",
     "match_terms": ["EVOLENT HEALTH"]},
    {"ticker": "EBS",  "name": "Emergent BioSolutions",
     "match_terms": ["EMERGENT BIOSOLUTIONS", "EMERGENT BIODEFENSE"]},

    # ============ CONSTRUCTION / INFRASTRUCTURE ============
    # All entries in this section also alert when the company is large/mega cap.
    {"ticker": "MTRX", "name": "Matrix Service",
     "match_terms": ["MATRIX SERVICE"], "include_when_large": True},
    {"ticker": "GVA",  "name": "Granite Construction",
     "match_terms": ["GRANITE CONSTRUCTION"], "include_when_large": True},
    {"ticker": "TPC",  "name": "Tutor Perini",
     "match_terms": ["TUTOR PERINI", "TUTOR-PERINI"], "include_when_large": True},
    {"ticker": "MYRG", "name": "MYR Group",
     "match_terms": ["MYR GROUP"], "include_when_large": True},
    {"ticker": "STRL", "name": "Sterling Infrastructure",
     "match_terms": ["STERLING INFRASTRUCTURE", "STERLING CONSTRUCTION"], "include_when_large": True},
    {"ticker": "PRIM", "name": "Primoris Services",
     "match_terms": ["PRIMORIS"], "include_when_large": True},
    {"ticker": "DY",   "name": "Dycom Industries",
     "match_terms": ["DYCOM"], "include_when_large": True},
    {"ticker": "GLDD", "name": "Great Lakes Dredge & Dock",
     "match_terms": ["GREAT LAKES DREDGE"], "include_when_large": True},
    {"ticker": "ROAD", "name": "Construction Partners",
     "match_terms": ["CONSTRUCTION PARTNERS"], "include_when_large": True},
    {"ticker": "STN",  "name": "Stantec",
     "match_terms": ["STANTEC"], "include_when_large": True},
    {"ticker": "J",    "name": "Jacobs Solutions",
     "match_terms": ["JACOBS SOLUTIONS", "JACOBS ENGINEERING", "JACOBS TECHNOLOGY", "JACOBS PROJECT"], "include_when_large": True},
    {"ticker": "FLR",  "name": "Fluor Corporation",
     "match_terms": ["FLUOR CORPORATION", "FLUOR FEDERAL", "FLUOR CONSTRUCTORS", "FLUOR GOVERNMENT"], "include_when_large": True},
    {"ticker": "FIX",  "name": "Comfort Systems USA",
     "match_terms": ["COMFORT SYSTEMS"], "include_when_large": True},

    # ============ ELECTRICAL / POWER INFRASTRUCTURE ============
    # All entries in this section also alert when the company is large/mega cap.
    {"ticker": "PWR",  "name": "Quanta Services",
     "match_terms": ["QUANTA SERVICES"], "include_when_large": True},
    {"ticker": "EME",  "name": "EMCOR Group",
     "match_terms": ["EMCOR GROUP", "EMCOR GOVERNMENT"], "include_when_large": True},
    {"ticker": "MTZ",  "name": "MasTec",
     "match_terms": ["MASTEC"], "include_when_large": True},
    {"ticker": "IESC", "name": "IES Holdings",
     "match_terms": ["IES HOLDINGS", "INTEGRATED ELECTRICAL SERVICES"], "include_when_large": True},
    {"ticker": "VMI",  "name": "Valmont Industries",
     "match_terms": ["VALMONT"], "include_when_large": True},
    {"ticker": "ATKR", "name": "Atkore",
     "match_terms": ["ATKORE"], "include_when_large": True},
    {"ticker": "AYI",  "name": "Acuity Brands",
     "match_terms": ["ACUITY BRANDS", "ACUITY LIGHTING"], "include_when_large": True},
    {"ticker": "HUBB", "name": "Hubbell",
     "match_terms": ["HUBBELL INCORPORATED", "HUBBELL POWER", "HUBBELL LIGHTING"], "include_when_large": True},
    {"ticker": "LMB",  "name": "Limbach Holdings",
     "match_terms": ["LIMBACH"], "include_when_large": True},
    {"ticker": "AGX",  "name": "Argan",
     "match_terms": ["GEMMA POWER", "ARGAN INC"], "include_when_large": True},
    {"ticker": "ETN",  "name": "Eaton Corporation",
     "match_terms": ["EATON CORPORATION", "EATON AEROSPACE"], "include_when_large": True},
    {"ticker": "ROK",  "name": "Rockwell Automation",
     "match_terms": ["ROCKWELL AUTOMATION"], "include_when_large": True},
    {"ticker": "EMR",  "name": "Emerson Electric",
     "match_terms": ["EMERSON ELECTRIC"], "include_when_large": True},
    {"ticker": "GEV",  "name": "GE Vernova",
     "match_terms": ["GE VERNOVA", "VERNOVA"], "include_when_large": True},
    {"ticker": "HON",  "name": "Honeywell International",
     "match_terms": ["HONEYWELL INTERNATIONAL", "HONEYWELL FEDERAL", "HONEYWELL TECHNOLOGY"], "include_when_large": True},
    {"ticker": "TT",   "name": "Trane Technologies",
     "match_terms": ["TRANE TECHNOLOGIES", "TRANE U.S."], "include_when_large": True},
    {"ticker": "CARR", "name": "Carrier Global",
     "match_terms": ["CARRIER GLOBAL", "CARRIER CORPORATION"], "include_when_large": True},
    {"ticker": "JCI",  "name": "Johnson Controls",
     "match_terms": ["JOHNSON CONTROLS"], "include_when_large": True},

    # ============ FACILITY SERVICES / ENVIRONMENTAL ENGINEERING ============
    # All entries in this section also alert when the company is large/mega cap.
    {"ticker": "TTEK", "name": "Tetra Tech",
     "match_terms": ["TETRA TECH"], "include_when_large": True},
    {"ticker": "KBR",  "name": "KBR Inc",
     "match_terms": ["KBR INC", "KELLOGG BROWN", "KBR SERVICES", "KBRWYLE", "KBR WYLE"], "include_when_large": True},
    {"ticker": "ABM",  "name": "ABM Industries",
     "match_terms": ["ABM INDUSTRIES", "ABM FACILITY", "ABM GOVERNMENT"], "include_when_large": True},
    {"ticker": "BV",   "name": "BrightView Holdings",
     "match_terms": ["BRIGHTVIEW"], "include_when_large": True},
    {"ticker": "ACM",  "name": "AECOM",
     "match_terms": ["AECOM"], "include_when_large": True},

    # ============ ENERGY / INDUSTRIAL / OTHER ============
    {"ticker": "OII",  "name": "Oceaneering International",
     "match_terms": ["OCEANEERING"]},
    {"ticker": "CECE", "name": "CECO Environmental",
     "match_terms": ["CECO ENVIRONMENTAL"]},
    {"ticker": "MG",   "name": "Mistras Group",
     "match_terms": ["MISTRAS"]},
    {"ticker": "WCC",  "name": "WESCO International",
     "match_terms": ["WESCO INTERNATIONAL", "WESCO DISTRIBUTION"]},
    {"ticker": "POWL", "name": "Powell Industries",
     "match_terms": ["POWELL INDUSTRIES"]},

    # ============ LARGE-CAP DEFENSE / AEROSPACE PRIMES ============
    # Big primes -- cap-band would normally exclude them; flag opens that.
    {"ticker": "LHX",  "name": "L3Harris Technologies",
     "match_terms": ["L3 HARRIS", "L3HARRIS", "HARRIS CORPORATION", "L-3 COMMUNICATIONS"], "include_when_large": True},
    {"ticker": "LDOS", "name": "Leidos Holdings",
     "match_terms": ["LEIDOS"], "include_when_large": True},
    {"ticker": "BAH",  "name": "Booz Allen Hamilton",
     "match_terms": ["BOOZ ALLEN"], "include_when_large": True},
    {"ticker": "TXT",  "name": "Textron",
     "match_terms": ["TEXTRON SYSTEMS", "TEXTRON AVIATION", "BELL TEXTRON", "TEXTRON INC"], "include_when_large": True},
    {"ticker": "TDG",  "name": "TransDigm Group",
     "match_terms": ["TRANSDIGM"], "include_when_large": True},
    {"ticker": "HEI",  "name": "Heico Corporation",
     "match_terms": ["HEICO"], "include_when_large": True},
    {"ticker": "HWM",  "name": "Howmet Aerospace",
     "match_terms": ["HOWMET AEROSPACE"], "include_when_large": True},
    {"ticker": "TDY",  "name": "Teledyne Technologies",
     "match_terms": ["TELEDYNE"], "include_when_large": True},
    {"ticker": "CVU",  "name": "CPI Aerostructures",
     "match_terms": ["CPI AEROSTRUCTURES"]},

    # ============ CYBERSECURITY ============
    {"ticker": "PANW", "name": "Palo Alto Networks",
     "match_terms": ["PALO ALTO NETWORKS"], "include_when_large": True},
    {"ticker": "CRWD", "name": "CrowdStrike Holdings",
     "match_terms": ["CROWDSTRIKE"], "include_when_large": True},
    {"ticker": "FTNT", "name": "Fortinet",
     "match_terms": ["FORTINET"], "include_when_large": True},
    {"ticker": "OKTA", "name": "Okta Inc",
     "match_terms": ["OKTA INC"], "include_when_large": True},
    {"ticker": "NET",  "name": "Cloudflare",
     "match_terms": ["CLOUDFLARE"], "include_when_large": True},
    {"ticker": "ZS",   "name": "Zscaler",
     "match_terms": ["ZSCALER"], "include_when_large": True},
    {"ticker": "S",    "name": "SentinelOne",
     "match_terms": ["SENTINELONE", "SENTINEL ONE"], "include_when_large": True},
    {"ticker": "FFIV", "name": "F5 Inc",
     "match_terms": ["F5 NETWORKS", "F5 INC"], "include_when_large": True},
    {"ticker": "ATEN", "name": "A10 Networks",
     "match_terms": ["A10 NETWORKS"]},

    # ============ FEDERAL IT RESELLERS / VARS ============
    {"ticker": "CDW",  "name": "CDW Corporation",
     "match_terms": ["CDW GOVERNMENT", "CDW CORPORATION", "CDW LLC"], "include_when_large": True},
    {"ticker": "NSIT", "name": "Insight Enterprises",
     "match_terms": ["INSIGHT PUBLIC SECTOR", "INSIGHT ENTERPRISES", "INSIGHT DIRECT"], "include_when_large": True},
    {"ticker": "PLUS", "name": "ePlus Inc",
     "match_terms": ["EPLUS TECHNOLOGY", "EPLUS INC ", "EPLUS GOVERNMENT"]},
    {"ticker": "CNXN", "name": "PC Connection",
     "match_terms": ["PC CONNECTION", "GOVCONNECTION", "GOV CONNECTION"]},
    {"ticker": "KEYS", "name": "Keysight Technologies",
     "match_terms": ["KEYSIGHT"], "include_when_large": True},

    # ============ DATA / DEV / CLOUD SOFTWARE (big federal customers) ============
    {"ticker": "ESTC", "name": "Elastic NV",
     "match_terms": ["ELASTICSEARCH", "ELASTIC NV", "ELASTIC INC"], "include_when_large": True},
    {"ticker": "MDB",  "name": "MongoDB",
     "match_terms": ["MONGODB"], "include_when_large": True},
    {"ticker": "SNOW", "name": "Snowflake",
     "match_terms": ["SNOWFLAKE INC", "SNOWFLAKE COMPUTING"], "include_when_large": True},
    {"ticker": "DOCN", "name": "DigitalOcean Holdings",
     "match_terms": ["DIGITALOCEAN"]},
    {"ticker": "ASAN", "name": "Asana",
     "match_terms": ["ASANA INC"]},

    # ============ HEALTHCARE / LIFE SCIENCES (gov customers) ============
    {"ticker": "DGX",  "name": "Quest Diagnostics",
     "match_terms": ["QUEST DIAGNOSTICS"], "include_when_large": True},
    {"ticker": "LH",   "name": "Labcorp Holdings",
     "match_terms": ["LABORATORY CORPORATION OF AMERICA", "LABCORP"], "include_when_large": True},
    {"ticker": "TECH", "name": "Bio-Techne",
     "match_terms": ["BIO-TECHNE", "BIO TECHNE"], "include_when_large": True},
    {"ticker": "CRL",  "name": "Charles River Laboratories",
     "match_terms": ["CHARLES RIVER LABORATORIES"], "include_when_large": True},
    {"ticker": "IQV",  "name": "IQVIA Holdings",
     "match_terms": ["IQVIA"], "include_when_large": True},

    # ============ INDUSTRIAL / DIVERSIFIED (large infra & test) ============
    # All flagged include_when_large since these are dominantly large/mega cap.
    {"ticker": "AME",  "name": "Ametek",
     "match_terms": ["AMETEK"], "include_when_large": True},
    {"ticker": "ROP",  "name": "Roper Technologies",
     "match_terms": ["ROPER TECHNOLOGIES", "ROPER INDUSTRIES"], "include_when_large": True},
    {"ticker": "DOV",  "name": "Dover Corporation",
     "match_terms": ["DOVER CORPORATION"], "include_when_large": True},
    {"ticker": "ITW",  "name": "Illinois Tool Works",
     "match_terms": ["ILLINOIS TOOL WORKS"], "include_when_large": True},
    {"ticker": "WTS",  "name": "Watts Water Technologies",
     "match_terms": ["WATTS WATER", "WATTS REGULATOR"], "include_when_large": True},
    {"ticker": "AOS",  "name": "A. O. Smith Corporation",
     "match_terms": ["A. O. SMITH", "A O SMITH", "AO SMITH"], "include_when_large": True},

    # ============ EMERGING SPACE / DRONES / AUTONOMY ============
    {"ticker": "ONDS", "name": "Ondas Holdings",
     "match_terms": ["ONDAS HOLDINGS", "AMERICAN ROBOTICS"]},
    {"ticker": "UAVS", "name": "AgEagle Aerial Systems",
     "match_terms": ["AGEAGLE", "AG EAGLE"]},
    {"ticker": "INVZ", "name": "Innoviz Technologies",
     "match_terms": ["INNOVIZ"]},

    # ============ MARITIME / LOGISTICS (DOD CRAF & shipping) ============
    {"ticker": "ATSG", "name": "Air Transport Services Group",
     "match_terms": ["AIR TRANSPORT SERVICES GROUP", "ABX AIR", "ATSG INC"]},
    {"ticker": "HUBG", "name": "Hub Group",
     "match_terms": ["HUB GROUP"]},
    {"ticker": "KEX",  "name": "Kirby Corporation",
     "match_terms": ["KIRBY CORPORATION", "KIRBY INLAND MARINE", "KIRBY OFFSHORE"]},

    # ============ ENERGY / NUCLEAR FUEL ============
    {"ticker": "LEU",  "name": "Centrus Energy",
     "match_terms": ["CENTRUS ENERGY", "USEC INC"]},
]
